use Mix.Config

# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.

config :tmate, Tmate.Endpoint,
  http: [port: System.get_env("MASTER_HTTP_PORT", "4000") |> String.to_integer()],
  url: System.get_env("MASTER_BASE_URL", "") |> URI.parse() |> Map.to_list(),
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  cache_static_manifest: "priv/static/cache_manifest.json"
# XXX If SSL options are needed. See tmate-websocket for example
config :phoenix, :serve_endpoints, true

# Do not print debug messages in production
config :logger, level: :info

config :tmate, Tmate.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: System.get_env("PG_USERNAME", "postgres"),
  password: System.get_env("PG_PASSWORD", "postgres"),
  database: System.get_env("PG_DATABASE", "tmate_prod"),
  hostname: System.get_env("PG_HOSTNAME", "postgres"),
  pool_size: System.get_env("PG_POOLSIZE", "20") |> String.to_integer(),
  ssl: System.get_env("PG_SSL_CA_CERT") != nil,
  ssl_opts: [cacertfile: System.get_env("PG_SSL_CA_CERT")]
